version: '3.5'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db         

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-app
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - ./:/app


volumes:
  mongodb_data_container: